name: CMake Build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          md build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
          nmake
      - name: Archive artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: NoneRender_win32.zip
          path: |
            main.exe
            resource
