name: cmake-build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
      - name: Build
        shell: cmd
        run: |
          md build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
          nmake
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: RenderLab_win.zip
          path: |
            main.exe
            resource
            scripts
